In [39]:
import torch
from torch.nn import functional as F
import numpy as np

In [23]:
y_pred = torch.tensor([1, 0, 0, 0], dtype=torch.float32)
y_true = torch.tensor([1, 0, 0, 0], dtype=torch.float32)
loss_ce = torch.nn.CrossEntropyLoss()
print(loss_ce(y_pred, y_true))


y_pred = torch.tensor([0, 1, 0, 0], dtype=torch.float32)
y_true = torch.tensor([1, 0, 0, 0], dtype=torch.float32)
print(loss_ce(y_pred, y_true))

y_pred = torch.tensor([0, 1, 0, 0], dtype=torch.float32)
y_true = torch.tensor([1, 1, 1, 1], dtype=torch.float32)
print(loss_ce(y_pred, y_true))

tensor(0.7437)
tensor(1.7437)
tensor(5.9747)


In [51]:
y_pred = torch.tensor([1, 0, 0, 0], dtype=torch.float32)
y_true = torch.tensor([1, 0, 0, 0], dtype=torch.float32)
loss = torch.nn.CrossEntropyLoss()
print(loss(y_pred, y_true))

tensor(0.7437)


In [82]:
y_pred = torch.tensor([100, 1, 1, 1], dtype=torch.float32)
y_true = torch.tensor([1, 0, 0, 0], dtype=torch.float32)
loss = torch.nn.CrossEntropyLoss()
print(loss(y_pred, y_true))

tensor(-0.)


In [90]:
y_pred = torch.tensor([[100, 1, 1, 1]], dtype=torch.float32)
y_true = torch.tensor([0])
loss = torch.nn.CrossEntropyLoss()
print(loss(y_pred, y_true))

tensor(0.)


In [91]:
y_pred = torch.tensor([
    [100, 1, 1, 1],
    [1, 100, 1, 1],
], dtype=torch.float32)
y_true = torch.tensor([0,1])
loss = torch.nn.CrossEntropyLoss()
print(loss(y_pred, y_true))

tensor(0.)


In [77]:
y_pred = torch.tensor([1, 0, 0, 0], dtype=torch.float32)
y_true = torch.tensor([1, 0, 0, 0], dtype=torch.float32)
loss = torch.nn.CrossEntropyLoss(reduction="sum")
print(loss(y_pred, y_true))

tensor(0.7437)


In [54]:
y_pred = torch.tensor([1, 0, 0, 0], dtype=torch.float32)
y_true = torch.tensor([0.5, 0.5, 0.5, 0.5], dtype=torch.float32)
loss = torch.nn.CrossEntropyLoss()
print(loss(y_pred, y_true))

tensor(2.9873)


In [73]:
y_pred = torch.tensor([1, 0, 0, 0], dtype=torch.float32)
y_true = torch.tensor([0.5, 0.5, 0.5, 0.5], dtype=torch.float32)
loss = torch.nn.CrossEntropyLoss()
print(loss(y_pred, y_true))

tensor(2.9873)


In [74]:
torch.log_softmax(y_pred, dim=0)

tensor([-0.7437, -1.7437, -1.7437, -1.7437])

In [72]:
np.log(0.4754)

-0.7435987240560435

In [70]:
torch.log_softmax(y_pred, dim=0)

tensor([-0.7437, -1.7437, -1.7437, -1.7437])

In [69]:
a = torch.log_softmax(y_pred, dim=0)
print(torch.sum(a * torch.softmax(torch.tensor([0.5, 0.5, 0.5, 0.5]), dim=0)))
print(torch.sum(a * torch.tensor([0.5, 0.5, 0.5, 0.5]), dim=0))

tensor(-1.4937)
tensor(-2.9873)


In [45]:
y_pred = torch.tensor([1, 0, 0, 0], dtype=torch.float32)
y_true = torch.tensor([1, 0, 0, 0], dtype=torch.float32)
loss_ce = torch.nn.CrossEntropyLoss()

print(loss_ce(y_pred, y_true))
print(loss_ce(y_pred, y_pred))

tensor(0.7437)
tensor(0.7437)


In [48]:
torch.softmax(y_pred, dim=0)

tensor([0.4754, 0.1749, 0.1749, 0.1749])

In [49]:
np.log(0.4754)

-0.7435987240560435

In [43]:
y_true

tensor([5.])

In [41]:
loss_ce(y_pred, y_pred)

tensor(-0.)

In [17]:
y_pred.shape

torch.Size([4])

In [24]:
y_pred = torch.tensor([0, -1, 0, 0], dtype=torch.float32)
y_true = torch.tensor([1, 1, 1, 1], dtype=torch.float32)
print(loss_ce(y_pred, y_true))

tensor(5.8571)


In [28]:
y_pred = torch.tensor([1], dtype=torch.float32)
y_true = torch.tensor([5], dtype=torch.float32)
print(loss_ce(y_pred, y_true))

tensor(-0.)


In [33]:
input = torch.randn(3, 5, requires_grad=True)
target = torch.empty(3, dtype=torch.long).random_(5)
print(input, input.shape)
print(target, print(target.shape))
loss_ce(input, target)

tensor([[ 0.1672, -0.2708,  0.6756, -1.2223, -1.0712],
        [-1.9550, -0.8650,  1.6150, -1.3133,  0.0661],
        [-1.2380,  0.3109,  0.2098, -0.4588,  0.3681]], requires_grad=True) torch.Size([3, 5])
torch.Size([3])
tensor([1, 0, 4]) None


tensor(2.3034, grad_fn=<NllLossBackward0>)

In [35]:
input = torch.randn(1, 5, requires_grad=True)
target = torch.randn(1, 5).softmax(dim=1)
loss_ce(input, target)

tensor(1.6508, grad_fn=<DivBackward1>)

In [37]:
input = torch.randn(1, 5, requires_grad=True)[0]
print(input.shape)
target = torch.randn(1, 5).softmax(dim=1)[0]
loss_ce(input, target)

torch.Size([5])


tensor(1.6209, grad_fn=<DivBackward1>)

In [40]:
np.log(1)

0.0